version: "3.8"

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: app-production
    volumes:
      - app-code-production:/var/www
      - storage-production:/var/www/storage/app/public
    env_file:
      - ../../.env.prod
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db-production
    environment:
      MYSQL_ROOT_PASSWORD: rizal8
      MYSQL_DATABASE: pc24_project
      MYSQL_USER: rizal
      MYSQL_PASSWORD: rizal8
    ports:
      - "3308:3306"
    volumes:
      - db-data-production:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-production
    volumes:
      - app-code-production:/var/www
      - storage-production:/var/www/storage/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.production.rule=Host(`a2.pc24.co.id`)"
      - "traefik.http.routers.production.entrypoints=websecure"
      - "traefik.http.routers.production.tls.certresolver=myresolver"
    networks:
      - app-network
      - traefik-network

volumes:
  app-code-production:
  storage-production:
  db-data-production:

networks:
  app-network:
    driver: bridge
  traefik-network:
    external: true
