version: "3.8"

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: app-staging
    volumes:
      - app-code-staging:/var/www
      - storage-staging:/var/www/storage/app/public
    env_file:
      - ../../.env.staging
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db-staging
    environment:
      MYSQL_ROOT_PASSWORD: rizal8
      MYSQL_DATABASE: pc24_project
      MYSQL_USER: rizal
      MYSQL_PASSWORD: rizal8
    ports:
      - "3307:3306"
    volumes:
      - db-data-staging:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-staging
    volumes:
      - app-code-staging:/var/www
      - storage-staging:/var/www/storage/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.staging.rule=Host(`a2.staging.pc24.co.id`)"
      - "traefik.http.routers.staging.entrypoints=websecure"
      - "traefik.http.routers.staging.tls.certresolver=myresolver"
    networks:
      - app-network
      - traefik-network

volumes:
  app-code-staging:
  storage-staging:
  db-data-staging:

networks:
  app-network:
    driver: bridge
  traefik-network:
    external: true
